spring.application.name=PlayerHive

# MONGODB
 spring.data.mongodb.uri=mongodb://localhost:27017/PlayerHive
# spring.data.mongodb.uri=mongodb://L1:27017,L2:27017,L3:27017/PlayerHive?replicaSet=rs0&w=1&readPreference=nearest

# NEO4J
 spring.neo4j.uri=bolt://localhost:7687
# spring.neo4j.uri=bolt://L3:7687

spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=00000000